### ISSUE TITLE
Sharex upload bug over 100MB files. [BUG]

### ISSUE THREAD

**Issue by 3k2** [BobbyWibowo/lolisafe#162]
**Describe the bug**

**To Reproduce**
1. Go to sharex
2. Click on upload file larger than 100MB
3. wait till the upload fails
4. Error message:

> Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
> 
> Request URL:
> https://safe.0x0.la/api/upload
> 
> Stack trace:
>    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
>    at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
>    at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Expected behavior**

should upload the file to the 0x0.la

**Screenshots**

**Additional context**

I believe this is issue is something to do with cloudflare I have reported this in the past for other lolisafe hosts and same type.

**Comment by samstarnes** [comment]
Might be an error with my server. Might be Lolisafe. I'm out so it's not easy for me to provide any additional logs for Bobby. I can provide those later when I'm home. I'll do a restart as of right now remotely.

**Comment by BobbyWibowo** [comment]
> Cloudflare limits upload size (HTTP POST request size) per plan type:
> - 100MB Free and Pro
> - 200MB Business
> - 500MB Enterprise by default (contact Customer Support to request a limit increase)
>
> If you require larger uploads, either:
> - **chunk requests smaller than the upload thresholds**, or
> - upload the full resource through a grey-clouded DNS record.
>
> More: https://support.cloudflare.com/hc/en-us/articles/200172516#h_51422705-42d0-450d-8eb1-5321dcadb5bc

The only reason anything bigger than 100MB is even working through the homepage uploader is because I had implemented the emboldened solution above into this fork.
But that would only work with the homepage uploader.
How ShareX upload files is beyond my control.
I can only tell ShareX where to upload and what headers to attach through the config.
In short, ShareX does NOT chunk uploads, hence you're limited by the limits above.

As to why anything bigger than 100MB is currently working with my safe, safe.fiery.me, through ShareX, that's only because I'm currently NOT using Cloudflare.

Anyway, in conclusion, you have the following options:
- Pester ShareX devs to implement chunked uploads, which I may add should be easy to hook into, especially through a mere config file.
- Don't use ShareX for any files bigger than the limits.
- Purchase higher tier Cloudflare plan.
- Add a grey-clouded DNS record, and use that specifically for ShareX config (you will expose your server's IP).
- Don't use Cloudflare (same as above).

> I believe this is issue is something to do with cloudflare I have reported this in the past for other lolisafe hosts and same type.

Yes.

**Comment by 3k2** [comment]
> As to why anything bigger than 100MB is currently working with my safe, safe.fiery.me, through ShareX, that's only because I'm currently NOT using Cloudflare

Ah yes I remember telling few other hosts who also had something like 8GB filesize limit and had issues with sharex they then later disabled cloudflare to allow bigger uploads..
