### ISSUE TITLE
[FEATURE REQUEST] captcha

### ISSUE THREAD

**Issue by ghost** [BobbyWibowo/lolisafe#187]
Implement captcha for signup page. Because google is starting to charge for reCaptcha (and recaptcha is just hell for anyone who doesn't use chrome), something like hcaptcha or a self-made one makes sense.

This solves the issue of automatic account creation, easily bypassing limits.

**Comment by BobbyWibowo** [comment]
I'm somewhat interested in this as well, but I don't particularly have the time to look into it for now.
If someone else is interested in picking it up, feel free. ~~Otherwise I'll probably give it a try in a few weeks.~~

**EDIT:** Unfortunately I still don't have time for this. Not sure when I'll be free enough to look into it.

**Comment by BobbyWibowo** [comment]
Ah yes, I think I'll like hCaptcha more. Their Privacy Pass thing is pretty interesting. It's already somewhat nice to have due to the amount of websites using Cloudflare out there, and the fact that I'm almost most of the time behind VPN, which sometimes trigger Cloudflare's captcha on websites with high security level.
For those who aren't aware, check out this article: https://blog.cloudflare.com/cloudflare-supports-privacy-pass/
