### ISSUE TITLE
Files uploaded, link produced, 404 error upon clicking link

### ISSUE THREAD

**Issue by GabenCrying** [BobbyWibowo/lolisafe#551]
The files are in the servers upload folder, produces a clickable link but upon clicking the link  we get 

`Resource not found 404
The requested resource could not be found.`

I thought maybe a permissions issue, but the perms look good
Link to perms list: https://pastebin.com/FGLDQxs7

Sorry for making two tickets in one day, lol

Heres my nginx file if it's relevant 
http://0x0.st/ojCb.txt (Look familiar? Rofl)

**Comment by GabenCrying** [comment]
Cure! 

In config.js, changed this to true 
`
serveFilesWithNode: true,`

**Comment by BobbyWibowo** [comment]
Yeah, you'll need a more elaborate NGINX config if you choose NOT to serve files with node (i.e. having that option turned off)

It's turned off by default since it's technically the better option (in terms of overall performance), despite requiring a bit more technical know-hows, unless you have other needs
Something like this: https://github.com/BobbyWibowo/lolisafe/blob/safe.fiery.me/docker/nginx/lolisafe.tld.http.example.conf#L14-L24
